<?php

namespace troisWA\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function listByDateDesc()
    {
        //on utilise la methode createQueryBuilder pour construire une requete
        //on met "a" en parametre car c'est l'initaile de la table concernée (-> ça fera "as a" dans la requete
        $queryBuilder = $this->createQueryBuilder("a");

        $articlesList = $queryBuilder
            //construction de la requete
            ->addOrderBy('a.articleDate', 'ASC')
            //->where('articleDate<:date')
            //->setParameter('date', $dateMax)
            ->getQuery()
            ->getArrayResult();
        // ou ->getResults(); à la place de ->getArrayResult();
        //print_r($queryBuilder);

        //autre façon d'écrire la requete :
        //$articlesList = $querryBuilder
        //createNativeQuerry('écrire la requete sql' )
        //->getQuery()
        //->getArrayResult();

        return $articlesList;

    }


}
